development:
  host: localhost
  database: gurusorocaba_development

test:
  host: localhost
  database: gurusorocaba_test

# set these environment variables on your prod server
production:
  host: localhost
  # username: <%= ENV['MONGOID_USERNAME'] %>
  # password: <%= ENV['MONGOID_PASSWORD'] %>
  database: gurusorocaba_production
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
